#!/usr/bin/env ruby

require 'json'
require "tty-prompt"


unless File.size? 'cloudflare-api'
  puts 'Cannot found cloudflare api file'

  File.open('cloudflare-api', 'w') do |f|
    prompt = TTY::Prompt.new
    f.puts prompt.ask('zone id:')
    f.puts prompt.mask('api token:')
  end
end
zone, token = File.open('cloudflare-api', &:read).split("\n")

file =
  `git diff --name-status -z gh-pages gh-pages~` \
  .split("\0") \
  .each_slice(2) \
  .each_with_object([]) do |x, changed|
    next unless x[0] == 'M'
    changed << "https://blog.yahvk.ml/#{x[1]}"
  end

data =
  if file == 'all' || file.size > 20
    { purge_everything: true }
  elsif file
    file << 'https://blog.yahvk.ml/'
    { files: file }
  else
    exit
  end

puts data.to_json

puts `curl -X DELETE \
  "https://api.cloudflare.com/client/v4/zones/#{zone}/purge_cache" \
  -H "Content-Type:application/json" \
  -H "Authorization: Bearer #{token}" \
  --data '#{data.to_json}'`
